### ISSUE TITLE
Legacy example doesn't work

### ISSUE THREAD

**Issue by etienne-napoleone** [mars-protocol/cw-asset#2]
Based on the example at https://docs.rs/cw-asset/0.3.4/cw_asset/#legacy-feature, get error:

> the trait bound `Asset: From<AssetBase<cosmwasm_std::addresses::Addr>>` is not satisfied
required because of the requirements on the impl of `Into<Asset>` for `AssetBase<cosmwasm_std::addresses::Addr>`

Cargo.toml
```toml
[package]
name = "test-assetinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-asset = { version = "0.3.3", features = ["legacy"] }
astroport = "1.0.1"
```

main.rs
```rust
fn main() {
    let a = cw_asset::Asset::native("uusd", 1u128);
    let b: astroport::asset::Asset = a.into();
}
```
